name: school_library
description: Offline library management for school.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.0
  # QR generation
  qr_flutter: ^4.1.0
  # Scanning (desktop + mobile)
  flutter_zxing: ^1.4.0
  # Printing labels
  pdf: ^3.10.4
  printing: ^5.11.1
  # UI helpers
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true